name: Backend CI

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vitest
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    name: Run backend tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            backend/
          sparse-checkout-cone-mode: false
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: ./server/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: ./backend
        run: pnpm i
      - name: Migrate schema
        working-directory: ./backend
        run: pnpm drizzle-kit push
        env:
          POSTGRES_CONNECTION: postgresql://postgres:postgress@localhost:5432/vitest
      - name: Test with coverage
        working-directory: ./server
        run: pnpm test
        env:
          MODE: CI
          POSTGRES_CONNECTION: postgresql://postgres:postgress@localhost:5432/vitest
